---
title: "Is the House the Only Winner? How Sports Betting Can Improve Local Communities"
author: "Tyler Castriotta"
date: "2024-1-29"
output: 
    html_document:
        theme: journal
    pdf_document:
        latex_engine: xelatex
urlcolor: blue
knit: (function(inputFile, encoding) {
 rmarkdown::render(inputFile, encoding = encoding, 
 output_format = 'all') 
 })
bibliography: references.bib
---

#### Introduction
<br>
There has been a long standing phrase that the house always wins. To corroborate that story, the Wall Street Journal did a study where they observed the performance of 4,222 gamblers. The result was that only 13.5% of bettors made a profit and that 217 people lost more than \$5000, while only 7 won more than that [@MaremontBerzon2013]. And if you strictly look at sports bettors, the outlook is much more grim. According to the website ElitePickz, only 3% of sports bettors are profitable [@Harrelson2024]. The former is definitely a stark number, especially when you contemplate exactly how much the other 97% might have lost altogether. Or you could spin it the other way and think about how much taxes on winnings the casinos and sports books are paying to their state. In fact, the main argument for legalizing sports betting, as well as why this topic is so important, was the amount of tax revenue that states would earn, which would go towards funding education, public works, and youth sports. Since the opening of mobile sports betting, the state of New York has generated \$1B that will go  directly towards education funding [@AddabboJr2023]. Why does this matter? Well, there has been many studies done that show a correlation between an increase in education funding and student achievement. One study in particular, done by Daniel Kreisman and Matthew P. Steinberg for the Journal of Public Economics. The article looks at how an increase in funding improves student achievement in the form of reading and math scores. With an increase in \$1000, reading and math scores increase by .1 sd and .08 sd, respectively on average [@KreismanSteinberg2019]. Because sports betting improves funding for public goods and due to government policy, this is rooted in public economics. 
<br>
#### Research Question
<br>
The research question that I will focus on in this paper is, <b>how does the legalization of sports betting affect state budgets?</b> I hypothesize that the legalization of sports betting will significantly increase a state's budget. If this hypothesis is true, it gives even more reason for states that have not legalized sports betting to do so.
<br>
#### Proposal of Research
<br>
I will be looking at how sports betting affects state budgets. On intuition alone, I believe that sports betting will have a significant impact at increasing a state budget, and therefore provide adequate funds to support public goods within a community, possibly even targeting communities that are typically underfunded or a district where there school system is under performing (this can be based on metrics such as: low standardized test scores, below average graduation rate, or higher than average drop out rate). 
<br>
There a couple things that may influence the results of this paper. One is that the lack of popularity in sports may translate to a smaller increase in state budgets, or even be crowded out by state lotteries that are easier for people to enter/understand than sports betting may be, especially if they do not know the rules of a given sport. I fear that this could be the case in states where there are no professional sports teams, a small number of professional sports, or a lack of popularity in their collegiate sports teams. Examples would be Montana or New Mexico, where there are no professional sports teams and lower popularity in there collegiate sports teams. It is important to look at these states, along with states that have an incredibly popular sports culture, to see if the legalization of sports betting contributes to the state budget.
<br>
Another factor that could influence the results of this paper is that sports betting will act as a substitute, rather than a compliment, to state lotteries. If this is the case, the increase in budget could be relatively small, if there is an increase at all. This could be present in states with a vibrant sports culture. If this is the case, the legalization of sports betting could simply be a net-negative(gives another way to problem gambling, addiction, loss of significant money). 
<br>
Not only could sports betting act as a substitute for casino gambling(i.e. video lottery terminal gaming or slots, blackjack, poker, etc.). An article, based on a case study in West Virginia, that introduced this possible challenge to me was "Legalized Sports Betting, VLT Gambling, and State Gambling Revenues: Evidence from West Virginia" by Brad R. Humphreys. The finding of this article was that West Virgina only added \$2.6 Million Dollars in sports betting revenue, yet lost \$45.4 Million dollars in VLT gaming revenue [@Humphreys2021]. The substantial difference of \$42.8 Million in revenue, in addition with a possible addition of problem gamblers by way of the introduction of sports betting could be detrimental to the state economy. The reason for saying could be is I need to be cognizant of the percentage of tax revenue that is brought in my gambling of all forms against other forms of tax revenue(sales tax, income tax, estate tax etc.). 

<br>
#### Relevant Literature
<br>
The most influential piece of literature for my thesis will be a research report done by the Social and Economic Impacts of Gambling in Massachusetts, or SEIGMA, titled, "Legalized Sports Betting in the United States and Potential Impacts in Massachusetts. The report contains just about every subtopic regarding to sports betting, such as: the difference in how sports betting operates by each state, outcomes of sports betting, and the differences in how sportsbooks and casinos are taxed [@SEIGMA2022}. In addition, the report also includes different literature review sections and data for each subtopic. This will go a long way in giving me ideas on how to illustrate the ful picture of how state economies are affected by the legalization of sports betting. Not only that, but it has been instrumental in teaching me topics revolving around al types of gamblihng that I had not known beforehand. 
<br>
As I have mentioned above, the Humphreys article gives insight to the issue of sports betting crowding out other forms of gambling. Obviously, this must be measured state-by-state, but it does talk to what I have said before about the lack of popularity in sports within a state. In this case, the gambling form that is crowding out the others is sports gambling, which is quite surprising to me as there are no professional sports teams in West Virginia. The results are not the only thing that intrigues me about this paper. I appreciate how Humphreys breaks down the demand for sports betting within a given week into each respective sports league, finding that the more NFL and NBA games there are, the more handle sports books and casinos receive [@Humphreys2021]. Just to give a brief description, handle is simply the amount of money bettors wage. I would like to do something similar in my own paper.
<br>
You can not talk about sports betting and not address the negatives that can come out of it, most notably problem gambling. One quite shocking finding was a study done in Australia that found that 46% of all dollars waged by sports bettors were from people with moderate to severe gambling problems [@ArmstongCarroll2017]. Proponents for sports betting usually say that the revenue from it will go to public goods like education. But, is it ethical to feed off an addiction as crippling as gambling. In their study, as well, they found that men aged 18-29, who are single and renting their place of docile, are more likely to experience gambling problems [@ArmstrongCarroll2017]. Perhaps the prevalence of this demographic within a state will lead to different revenue outcomes or different gambling addiction assitance programming/funding.
<br>
#### Added Contributions of Work

The legalization of sports betting is rather new so I will be looking at data and the effects of sports betting in real-time. In addition that, people who are pro-legalization of sports betting tend to give relatively the same reason for why they think that way: an addition of tax revenue, possible creation of jobs, and to make games more interesting. to further that third point, in an advertisement, Draft Kings, one of the biggest online sports betting companies along with FanDuel,  stated that "life is more fun with skin in the game.". That may be so, but are there actual tangible economic benefits that come from sports betting or is it just another form of entertainment that could spiral out of control leading to financial loss for the bettor. That is what I will be trying to find out. Lastly, there has no been an abundance of literature where thwy subsetted the states into different categories (in this paper it will be about popularity of sports measured through number of professional sports team around them or national collegiate sport powerhouses) to see if is worth it to have sports betting in all states, some states, or no states at all.

#### Data
<br>
Ideally, there would be data for state tax revenues for sports betting and gambling, the percentage of state tax revenue that the two make up, and the percentage of problem gamblers in a given state. To the first subject, I will be using the Motley Fool website(motleyfool.com) to access the tax revenue and amount of handle for each state and the "State of the State" annual reports done by the American Gaming Association. One challenge I will face is the recency of the legalization of sports betting that may skew my results. For example, if I subset the data to look at states where sports are very popualr (i.e. the increased number of professional sports teams), I would have to include Massachusetts. Yet, sports betting has only been legal in Massachusetts for less than a year and as such the data could be misleading as newer things get more attention. What I could do the mend that issue is to look at how sports betting in states like Massachusetts: New York, Pennsylvannia, New Jersey, performed in their first couple of years post-legalization and then compare them; possibly creating qa forecast of how sports betting in  Massachusetts will look like. 
<br>
To the second topic, I will need to go more in the weeds to find tax revenue from more specific areas. For this, I will most likely have to look at revenue from each state government webpage. Tax Foundation (website - taxfoundation.org) has graphs of the different percentages for each tax revenue source, but gambling-related activities are included in the "other taxes" source, so that does not really do me much good. The challenge with this is just the amount of time that will need to be spent on it.
<br>
Lastly, surveys done in the aforementioned SEIGMA report, will help me visualize a percentage for problem gambling in each state. But finding specific numbers on how much problem gamblers add to the tax revenue like the Armstrong and Carroll report did, will be a little more challenging if it is even possible. Again, time will be against me as I am looking at all fifty states.

#### Sections for Thesis
<br>

Lit Review
<br> 
Costs and benefits odf sports betting
<br>
Methodology
<br>
Basic diff-in-diff of state budgets pre-and-post legaliztion to start and then Subset states into different categories based on popularity of states

<br>

#### Bibliogrpahy
<br>